version: "3.5"

services:
  kafka:
    container_name: kafka
    image: "docker.io/bitnami/kafka:latest" # 使用最新版本以支持Kraft模式
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_PROCESS_ROLES=broker,controller # 启用Kraft模式
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@localhost:9093 # 设置quorum voter
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
    volumes:
      - "kafka_data:/bitnami"

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui
    ports:
      - "9090:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092 # 注意这里不需要使用9093端口了

volumes:
  kafka_data:
    driver: local