server:
  port: 8075
spring:
  application:
    name: kafka-producer-serv
  kafka:
    bootstrap-servers: localhost:9092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/